version: "3"

services:
  backend:
    container_name: beam-server
    build:
      context: ./backend
      dockerfile: test.Dockerfile
    depends_on:
      - db
    ports:
      - "5055:5055"
    environment:
      - APP_KEY=testSecretKey
      - NODE_ENV=staging
      - DB_URL=mongodb://beam_db:beam_db_password@db:27017/beam?authSource=admin
      - GOOGLE_ID=992903294041-lp2gn624a9h5pakko33q6idlo704j6s9.apps.googleusercontent.com
      - GOOGLE_SECRET=qdlNGEXa8LsAM6va_U2tuZK8
      - GMAIL_USER=team@usebeam.chat
      - GMAIL_PASSWORD=qibezmprofkljudq
      - FACEBOOK_ID=1019743245095734
      - FACEBOOK_SECRET=fff24cbe988ec72cda051078b477a906
      - CLIENT_URL=http://localhost:3000
      - BOT_EMAIL=team@usebeam.chat
    volumes:
      - ./backend:/app/
      - /app/node_modules

  frontend:
    container_name: beam-web
    build:
      context: ./frontend
      dockerfile: test.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    tty: true
    volumes:
      - ./frontend:/app/
      - /app/node_modules

  db:
    container_name: beam-db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=beam_db
      - MONGO_INITDB_ROOT_PASSWORD=beam_db_password
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  server:
  client:
