version: "3"

services:
  backend:
    container_name: beam-server
    build:
      context: ./backend
      dockerfile: test.Dockerfile
    depends_on:
      - db
    ports:
      - "5055:5055"
    environment:
      - APP_KEY=testSecretKey
      - NODE_ENV=staging
      - DB_URL=mongodb://beam_db:beam_db_password@db:27017/beam?authSource=admin
      - GOOGLE_ID=992903294041-lp2gn624a9h5pakko33q6idlo704j6s9.apps.googleusercontent.com
      - GOOGLE_SECRET=qdlNGEXa8LsAM6va_U2tuZK8
      - GMAIL_USER=team@usebeam.chat
      - GMAIL_PASSWORD=qibezmprofkljudq
      - FACEBOOK_ID=1019743245095734
      - FACEBOOK_SECRET=fff24cbe988ec72cda051078b477a906
      - CLIENT_URL=http://localhost:3000
      - BOT_EMAIL=team@usebeam.chat
      - FIREBASE_PROJECT_ID=beam-abf91
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-r52q7@beam-abf91.iam.gserviceaccount.com
      - FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDGytSN4653nirj\nlwlQ2EzjM/N0M05zxHtN2UJSGRT8zGao0QnsbQjWbiTW0Noc7DM6nTMkk+LMM+vy\n3w7TijxuPmYougT8XqKjrNEi23T1Sn3m7qGE4ny7p13IiDdFrS0xHDoqLJ3l82+b\nMNTLbyj93qNB9trebZ8ePP8F+Yd0hxRVvfg3tEeAfAKbQphnSf9Zlqhfeb/6S9Qm\nuEpPvxMbfmwbP2tt8UYwdeUmlBEUYZy1PU12L65cj90h93QoLHZxD+327HvmhPDv\nUJtKygM1uJAkYWGyf9sQZggtSBzH5zQO9MoeqmuCiDPYKPJEW/pKufY9+isHvR+g\nSsPffH1/AgMBAAECggEAGjiAvCJu+HTStWhOS0KXNFS9j53WLZZEqVUMgWWw4Kiu\nqyUUyQGXa9PlZLbxk2UNsMqGshQWPdcPZTP0xwRHH5zNaXZ31+M8/UJ7PLzI+t2+\nKOq1lUsxJqisdG87KHlE1Q3Nwj2rqhFnrtxMWnT+vtWnSmPJehM9ggXg9s8eBcmG\nieO/NrtDjSWUTvXvRBrqXhy+0zbK4xGFYehWJJ56VYBkDBYi6bZ3RHpZq0ipMSqA\nx7hbW5vG9bBCPhr/QR+3Dset/dgexaW3/3pMOhrIyYRa75aEH3JGpkpYY85J1Ljt\ndHYR0MEU8aHrvxcEhZ2rwRKBwEESFPk+xZ27Pu7F4QKBgQDqsys8TFjGo02H8TQT\nm7P9JCSS2Ry+uqdjr3rcVF4fLWcC0EkyHTmjahH+c3lEBOljQL6idDmBf2lrsOGH\ntUyh8M5BQuq+AjabW1BEXoG+GzqadrEIGW4aJ6DF36x2YXD3Gg8bNqj2KBWlbXDh\nU8qUULfvtk9lirWX+HLeK9LwcQKBgQDY1WnNqghn4vZimeE9q1SBqPq6gAb2CeEi\n4dJuD+7HhzpNDkkbFUTts7byT0DuRgn4X/pCDc20YxTan2Vjn/f7AVrpxeaTnmF+\n5RFlgtp2KAgZZURxO0wSc5rSFBN2X+eHdLV7XzVNltD3hPb1r2tr1oqarhUtYC9P\nYb15oLBE7wKBgQDYp4CX7xpcc89UWJLsLuWeHsksTgO9BW0UFp9h2Pfx6+WVsVSA\nUH4unfHyZAJjie0wVEomiQe0xTs50FTBA9mz/ClKEU3FDSH/k/Gqy1sVdOlKQZr2\nkRMUTdSaFPqNZTH0yTd8tZ6PbT1eMoLrXoA5HbJONItifwNXQGA5O1dD4QKBgGTX\ng9hJPpWKAUpEBHPYzXlrrAe2aQZd+91sJqBXOpaC9oNFpIw67Q6baPbyEuF9oz9m\n641yu/srpVQzk0Ss7fhHXg+goSaAHxmT0O5j19PhtDqTVSxQBoYCS7tt6MtBuPzP\nM2PIGJMYE+E5bl0+kvfZFCbx1RmARSBm9Waua6vzAoGAWIUFBzGZAQvj+vrXZXPU\nkREMzo6y2msJ7u+qZTje2sJN/tzsNYtNjw6NsV4RHjBJwM+WLYoSycYcsXWGylAI\nXdJ4Ju6fHHA16iWasXLlMw4dCYrYJMUMOUSFZqJwQ5zyzwHKRF2V2ysHCwieKdoa\n/mHFB/zsgYuWteU6ai7yC3c=\n-----END PRIVATE KEY-----\n"
    volumes:
      - ./backend:/app/
      - /app/node_modules

  frontend:
    container_name: beam-web
    build:
      context: ./frontend
      dockerfile: test.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    tty: true
    volumes:
      - ./frontend:/app/
      - /app/node_modules

  db:
    container_name: beam-db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=beam_db
      - MONGO_INITDB_ROOT_PASSWORD=beam_db_password
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  server:
  client:
